spring:
  application:
    name: webflux-study
  r2dbc:
    url: r2dbc:mysql://admin:password@localhost/cloud_billing_dev?tcpKeepAlive=true&useServerPrepareStatement=true&tcpNoDelay=true&useSSL=false
    pool:
      initial-size: 10
      max-size: 30
      validation-query: SELECT 1
      enabled: true
      min-idle: 5
      max-life-time: 30m
      max-create-connection-time: 30000
      max-validation-time: 1000
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: always

